### ISSUE TITLE
This isn't markdown, it's reStructuredText

### ISSUE THREAD

**Issue by evaryont** [syropian/astral-issues#13]
https://github.com/audreyr/favicon-cheat-sheet doesn't use markdown nor plain-text for it's README, and therefore doesn't render properly.

However, it's still pretty close:

![astral_rendering_rst_as_md](https://cloud.githubusercontent.com/assets/14547/5178893/50b38bac-7432-11e4-8fc2-bf98815e6b72.PNG)

**Comment by syropian** [comment]
This issue was moved to astralapp/astral#4
