### ISSUE TITLE
Ability to edit tag directly at the tag list column

### ISSUE THREAD

**Issue by enginebai** [syropian/astral-issues#26]
Hi, is it possible edit the tag directly at the tag list column?? Thanks.
![2015-01-20 8 59 38](https://cloud.githubusercontent.com/assets/3387462/5810575/a000a794-a083-11e4-946c-7da3119d2322.png)

**Comment by thasmo** [comment]
Double-click or long-press would be nice.

**Comment by syropian** [comment]
Been thinking of a nice way to do this without cluttering the UI. Double-click would be fine, but non-obvious for a lot of people.

**Comment by syropian** [comment]
This issue was moved to astralapp/astral#12
