### ISSUE TITLE
Tag `Storage` doesn't work

### ISSUE THREAD

**Issue by thasmo** [syropian/astral-issues#28]
Repositories can be tagged but the tag shows a count of 0, although I have five tagged repositories. Also when typing the tag in the search field, it's not suggested. All other tags seem to work, only `Storage` behaves weird.

**Comment by thasmo** [comment]
Ah, nevermind - I had the tag `Storage` twice in the list - although I don't know if that should be possible.

**Comment by syropian** [comment]
Hm, I didn't think you could create duplicate tags, I'll look into this, thanks!
