### ISSUE TITLE
Ability To Share My Tags?

### ISSUE THREAD

**Issue by Gerst20051** [syropian/astral-issues#29]
@syropian is this on the radar?

**Comment by syropian** [comment]
Yep, definitely on my radar, just hoping to squash a few bugs and UX problems first, and then I can move on to more features :)

**Comment by hlfcoding** [comment]
In the meantime, you can run script below in the console directly in the app.
```js
// build repos
var repos = $('.repo').map(function(){
  var $el = $(this);
  var name = $el.find('.repo-name').text();
  var tags = $el.find('.repo-tags li').map(function() { return $(this).text(); }).get();
  return { name: name, tags: tags };
}).get();
// build tags from repos
var tags = [];
_.each(repos, function(repo) {
  _.each(repo.tags, function(name) {
    tag = _.findWhere(tags, { name: name });
    if (tag === undefined) {
      tag = { name: name, repos: [] };
      tags.push(tag);
    }
    tag.repos.push(repo);
  });
});
```
If you don't mind bookmarklets, there's also tools like, which will at least simplify part of the above. http://medialab.github.io/artoo

**Comment by syropian** [comment]
This issue was moved to astralapp/astral#14
